source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/elegion/ios-podspecs.git'

target 'ELNHTTPNetworking-RACExtensions_Example', :exclusive => true do
    pod 'ReactiveCocoa', '~> 2.5'
    pod 'ELNHTTPNetworking'
    pod 'ELNHTTPNetworking-RACExtensions', :path => '../'
end

target 'ELNHTTPNetworking-RACExtensions_Tests', :exclusive => true do
    pod 'ELNHTTPNetworking-RACExtensions', :path => '../'
end
